version: '3.9' # ファイルのバージョン

services:
  app: # サービス名は任意
    build: ./docker/php
    # ↑ビルドコンテキストを指定 → docker buildを実行する際の現在の作業ディレクトリのこと
    # Dockerfileが置かれているディレクトリ
    volumes:
      - ./src:/data # ./srcディレクトリをappのコンテナ内/dataへマウント

  web:
    # image: nginx:1.20-alpine # nginxは偶数が安定ver.
    image: nginx:1.22-alpine
    ports:
      - 8080:80 # ホスト側:コンテナ側
    volumes:
      - ./src:/data
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: